import { expect, test } from 'bun:test'
import * as fs from 'node:fs'
import * as os from 'node:os'
import * as path from 'node:path'
import {
	defaultPluginDir,
	installPlugin,
	pluginTarget,
	uninstallPlugin,
} from '../scripts/plugin-install'

function tempRepo(): string {
	const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'ar-install-repo-'))
	fs.writeFileSync(path.join(dir, 'autoresearch.ts'), 'export default function plugin() {}\n')
	return dir
}

test('default plugin directory uses Amp config path under home', () => {
	expect(defaultPluginDir(path.join('C:', 'Users', 'me'))).toBe(
		path.join('C:', 'Users', 'me', '.config', 'amp', 'plugins'),
	)
})

test('install creates the plugin entry and uninstall removes it', () => {
	const repoRoot = tempRepo()
	const pluginDir = fs.mkdtempSync(path.join(os.tmpdir(), 'ar-install-plugins-'))
	const message = installPlugin({ repoRoot, pluginDir })
	const target = pluginTarget(pluginDir)

	expect(message).toContain(target)
	expect(fs.existsSync(target)).toBe(true)

	uninstallPlugin({ pluginDir })
	expect(fs.existsSync(target)).toBe(false)
})

test('install can write an import shim when symlinks are unavailable', () => {
	const repoRoot = tempRepo()
	const pluginDir = fs.mkdtempSync(path.join(os.tmpdir(), 'ar-install-shim-'))
	const message = installPlugin({ repoRoot, pluginDir, mode: 'shim' })
	const target = pluginTarget(pluginDir)
	const installed = fs.readFileSync(target, 'utf-8')

	expect(message).toContain('as an import shim')
	expect(installed).toContain('Generated by amp-autoresearch installer')
	expect(installed).toContain('export { default } from "file://')
})
