import * as fs from 'node:fs'
import * as os from 'node:os'
import * as path from 'node:path'
import { pathToFileURL } from 'node:url'

export const PLUGIN_FILENAME = 'amp-autoresearch.ts'

export function defaultPluginDir(home = os.homedir()): string {
	return path.join(home, '.config', 'amp', 'plugins')
}

export function repoRootFromScript(): string {
	return path.resolve(import.meta.dir, '..')
}

export function pluginSource(repoRoot: string): string {
	return path.join(repoRoot, 'autoresearch.ts')
}

export function pluginTarget(pluginDir = defaultPluginDir()): string {
	return path.join(pluginDir, PLUGIN_FILENAME)
}

function shimContents(source: string): string {
	return `// Generated by amp-autoresearch installer.\nexport { default } from ${JSON.stringify(pathToFileURL(source).href)}\n`
}

export function installPlugin(
	options: { repoRoot?: string; pluginDir?: string; mode?: 'auto' | 'shim' } = {},
): string {
	const repoRoot = options.repoRoot ?? repoRootFromScript()
	const source = pluginSource(repoRoot)
	const dir = options.pluginDir ?? defaultPluginDir()
	const target = pluginTarget(dir)

	if (!fs.existsSync(source)) throw new Error(`Plugin source not found: ${source}`)
	fs.mkdirSync(dir, { recursive: true })
	if (options.mode === 'shim') {
		fs.rmSync(target, { force: true })
		fs.writeFileSync(target, shimContents(source), 'utf-8')
		return `Installed ${target} as an import shim for ${source}`
	}

	try {
		fs.rmSync(target, { force: true })
		fs.symlinkSync(source, target, 'file')
		return `Installed ${target} -> ${source}`
	} catch (e) {
		fs.writeFileSync(target, shimContents(source), 'utf-8')
		return `Installed ${target} as an import shim for ${source} (symlink unavailable: ${e instanceof Error ? e.message : String(e)})`
	}
}

export function uninstallPlugin(options: { pluginDir?: string } = {}): string {
	const target = pluginTarget(options.pluginDir ?? defaultPluginDir())
	fs.rmSync(target, { force: true })
	return `Removed ${target}`
}

if (import.meta.main) {
	const action = process.argv[2]
	try {
		const message = action === 'uninstall' ? uninstallPlugin() : installPlugin()
		console.log(message)
	} catch (e) {
		console.error(e instanceof Error ? e.message : String(e))
		process.exit(1)
	}
}
